Update virtual.js
Update required to allow for Braintree Virtual Terminal to submit a transaction.

Without this fix, the inspector console shows a JS error when the "Take Payment" Button is clicked.

virtual.js:145 Uncaught TypeError: this.$container.validate is not a function
    at UiClass.submitOrder (virtual.js:145:29)
    at HTMLFormElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at HTMLFormElement.<anonymous> (jquery.js:8797:30)
    at Function.each (jquery.js:385:35)
    at jQuery.fn.init.each (jquery.js:207:27)
    at jQuery.fn.init.trigger (jquery.js:8796:25)
    at $.<computed>.<computed>._click (button.js:48:31)
    at $.<computed>.<computed>._click (jquery-ui.js:143:41)